// --- DATA LAYER ---
const syllabusData = {
    alphabets: [
        { id: 'A', word: 'Ants', emoji: '🐜', color: 'bg-red-200', rhyme: "Ants on my arm, /a/ /a/ /a/\nAnts on my arm,\nThey’re causing me alarm." },
        { id: 'B', word: 'Bat', emoji: '🦇', color: 'bg-blue-200', rhyme: "Bring your bat and bring your ball,\n/b/ /b/ /b/\nBring your bat and bring your ball,\nTo the park to play!" },
        { id: 'C', word: 'Castanets', emoji: '🪇', color: 'bg-green-200', rhyme: "We are clicking castanets,\n/c/ /c/ /c/\nWe are clicking castanets,\n/c/ /c/ /c/\nWe are clicking castanets,\nClicking castanets,\n/c/ /c/ /c/" },
        { id: 'D', word: 'Drum', emoji: '🥁', color: 'bg-yellow-200', rhyme: "See me play upon my drum,\nPlaying drums is lots of fun!\nWith a /d/ /d/ /d/ /d/ /d/ /d/ /d/\nSee me play upon my drum." }
        // Add E-L here
    ],
    numbers: [
        { id: '1', word: 'One', emoji: '☝️', items: '🍎', rhyme: "Number 1, Number 1\nNumber 1 is straight and fun!" },
        { id: '2', word: 'Two', emoji: '✌️', items: '🍎🍎', rhyme: "Number 2, Number 2\nTwo kangaroos in the zoo!" },
        { id: '3', word: 'Three', emoji: '🤟', items: '🍎🍎🍎', rhyme: "Number 3, Number 3\nThree apples on a tree!" }
        // Add 4-10 here
    ],
    vegetables: [
        { word: 'Tomato', emoji: '🍅', color: 'bg-red-300', rhyme: " Which fruit is used to make ketchup?\n Tomato" },
        { word: 'Spinach', emoji: '🥬', color: 'bg-green-400', rhyme: "Which is the darkest green leafy vegetable?\n Spinach" },
        { word: 'Corn', emoji: '🌽', color: 'bg-yellow-200', rhyme: "Which vegetable has yellow ears?\n Corn plant" },
        { word: 'Seedless Veggies', emoji: '🥕', color: 'bg-orange-200', rhyme: "Name any 3 seedless vegetables.\n Cabbage, Carrot and potato" },
        { word: 'Peppers', emoji: '🫑', color: 'bg-red-400', rhyme: " Pepper colours are same as Traffic lights. Name them.\n Yellow, red and green." },
        { word: 'Seed Veggies', emoji: '🫛', color: 'bg-emerald-300', rhyme: " Name any 2 seed vegetables.\n Peas and beans" },
        { word: 'Tomato (Fruit)', emoji: '🍅', color: 'bg-rose-300', rhyme: " Which vegetable can also be called as fruit?\n Tomato" }
    ],
    birds: [
        { word: 'Ostrich', emoji: '🥚', color: 'bg-orange-200', rhyme: " Which bird lays many eggs in one nest?\n Ostrich" },
        { word: 'Hummingbird', emoji: '🐦', color: 'bg-teal-200', rhyme: " I am a bird. I can fly backward. Name me.\n Hummingbird" },
        { word: 'Crow', emoji: '🐦‍⬛', color: 'bg-gray-300', rhyme: " Which black bird is known for its intelligence?\n Crow" },
        { word: 'Penguin', emoji: '🐧', color: 'bg-blue-200', rhyme: " Which is the fastest swimming bird?\n Penguin" },
        { word: 'Eagle', emoji: '🦅', color: 'bg-amber-300', rhyme: " Which bird has the sharpest eyesight?\n Eagle" },
        { word: 'Owl', emoji: '🦉', color: 'bg-indigo-300', rhyme: " Which bird can see well at night?\n Owl" },
        { word: 'Flamingo', emoji: '🦩', color: 'bg-pink-300', rhyme: " Which bird often eats with its head upside down?\n Flamingo" },
        { word: 'Chirp', emoji: '🎵', color: 'bg-green-200', rhyme: " A bird's sound is called a ______.\n Chirp" },
        { word: 'No Teeth', emoji: '🦷', color: 'bg-red-200', rhyme: " Do birds have teeth?\n No" },
        { word: 'Diet', emoji: '🐛', color: 'bg-lime-200', rhyme: " What do birds eat?\n Seeds, fruits, berries and insects." },
        { word: 'Ostrich', emoji: '📏', color: 'bg-orange-300', rhyme: " Which is the largest bird in the world?\n Ostrich" },
        { word: 'Hummingbird', emoji: '🤏', color: 'bg-teal-300', rhyme: " Which is one of the smallest birds in the world?\n Hummingbird" },
        { word: 'Penguin', emoji: '🐧', color: 'bg-slate-200', rhyme: " I am a black-and-white bird who waddles around\nin the snow, like a man wearing a suit. Who am I?\n Penguin" },
        { word: 'Cannot Fly', emoji: '🚶', color: 'bg-yellow-200', rhyme: " Which birds cannot fly?\n Kiwi and Ostrich" },
        { word: 'Kite', emoji: '🪁', color: 'bg-cyan-200', rhyme: " Which bird can fly to great heights?\n Kite" },
        { word: 'Duck', emoji: '🦆', color: 'bg-blue-300', rhyme: " Which bird can swim?\n Duck" },
        { word: 'Cygnet', emoji: '🦢', color: 'bg-white', rhyme: " What is a baby swan called?\n Cygnet" },
        { word: 'Parrot', emoji: '🦜', color: 'bg-green-300', rhyme: " Which is the parrot's favourite game?\n Hide and Seek" },
        { word: 'Koyal', emoji: '🎶', color: 'bg-purple-200', rhyme: " Name a singing bird.\n Koyal" },
        { word: 'Peacock', emoji: '🦚', color: 'bg-emerald-200', rhyme: " Which is the national bird of India?\n Peacock" },
        { word: 'Quack-Quack', emoji: '🗣️', color: 'bg-yellow-300', rhyme: " What sound does a duck make?\n Quack-Quack" },
        { word: 'Chick', emoji: '🐥', color: 'bg-amber-200', rhyme: " What is a young hen called?\n Chick" }
    ],
    helpers: [
        { word: 'Doctor', emoji: '👨‍⚕️', color: 'bg-blue-100', rhyme: "Who treats sick people?\n Doctor" },
        { word: 'Teacher', emoji: '👩‍🏫', color: 'bg-green-100', rhyme: "Who helps us learn in school?\n Teacher" },
        { word: 'Police', emoji: '👮', color: 'bg-blue-300', rhyme: "Who catches thieves?\n Police" },
        { word: 'Firefighter', emoji: '👨‍🚒', color: 'bg-red-200', rhyme: "Who puts out fires?\n Firefighter" },
        { word: 'Postman', emoji: '📭', color: 'bg-yellow-100', rhyme: "Who delivers letters & parcels?\n Postman" },
        { word: 'Driver', emoji: '🚌', color: 'bg-purple-200', rhyme: "Who drives a bus?\n Driver" },
        { word: 'Builder', emoji: '🏗️', color: 'bg-orange-200', rhyme: "Who builds houses?\n Builder" },
        { word: 'Barber', emoji: '✂️', color: 'bg-teal-200', rhyme: "Who cuts our hair?\n Barber" },
        { word: 'Sweeper', emoji: '🧹', color: 'bg-gray-300', rhyme: "Who cleans our streets?\n Sweeper" },
        { word: 'Ambulance', emoji: '🚑', color: 'bg-red-300', rhyme: "Who helps during emergencies?\n Ambulance" },
        { word: 'Vet', emoji: '🐕', color: 'bg-emerald-200', rhyme: "Who takes care of animals?\n Vet" },
        { word: 'Hospital', emoji: '🏥', color: 'bg-pink-200', rhyme: "We go to (dash) when we are sick.\n Hospital" },
        { word: 'Stethoscope', emoji: '🩺', color: 'bg-blue-200', rhyme: "Which tool is used by a doctor?\n Stethoscope" },
        { word: 'Hose', emoji: '🚒', color: 'bg-red-400', rhyme: "Which tool is used by a firefighter?\n Hose" },
        { word: 'Brush', emoji: '🖌️', color: 'bg-yellow-300', rhyme: "Which tool is used by a painter?\n Brush" },
        { word: 'Cobbler', emoji: '👞', color: 'bg-stone-300', rhyme: "Who mends our shoes?\n Cobbler" },
        { word: 'Tailor', emoji: '🧵', color: 'bg-indigo-200', rhyme: "Who stitches our clothes?\n Tailor" },
        { word: 'Farmer', emoji: '🧑‍🌾', color: 'bg-green-300', rhyme: "Who grows crops?\n Farmer" },
        { word: 'Carpenter', emoji: '🪚', color: 'bg-amber-300', rhyme: "Who makes furniture?\n Carpenter" },
        { word: 'Milkman', emoji: '🥛', color: 'bg-slate-100', rhyme: "Who delivers milk?\n Milkman" },
        { word: 'Baker', emoji: '🧁', color: 'bg-pink-300', rhyme: "Who bakes cakes?\n Baker" },
        { word: 'Plumber', emoji: '🔧', color: 'bg-cyan-200', rhyme: "Who repairs pipes & taps?\n Plumber" },
        { word: 'Gardener', emoji: '🪴', color: 'bg-lime-200', rhyme: "Who helps us with gardening?\n Gardener" },
        { word: 'Vendor', emoji: '🛒', color: 'bg-orange-300', rhyme: "Who sells fruits & vegetables?\n Vendor" }
    ],
    bodySenses: [
        { word: 'Wrist', emoji: '⌚', color: 'bg-slate-200', rhyme: " The place where you wear a watch?\n Wrist" },
        { word: 'Teeth', emoji: '🦷', color: 'bg-gray-100', rhyme: " We chew food through our ______ .\n Teeth" },
        { word: 'Fingers', emoji: '🖐️', color: 'bg-amber-100', rhyme: " How many fingers do we have?\n 10" },
        { word: 'Nose', emoji: '👃', color: 'bg-orange-100', rhyme: " We smell food by which sense organ?\n Nose" },
        { word: 'Body Parts', emoji: '🧍', color: 'bg-teal-100', rhyme: " Name 6 different body parts.\n Head, Eyes, Ears, Lips, Hands and Legs" },
        { word: 'Eyes', emoji: '👀', color: 'bg-blue-100', rhyme: " What do we do with our eyes?\n See" },
        { word: 'Ears', emoji: '👂', color: 'bg-pink-100', rhyme: " What do we hear with?\n Ears" },
        { word: 'Hands', emoji: '🤝', color: 'bg-yellow-200', rhyme: " What do we do with our hands?\n Hold" },
        { word: 'Nose', emoji: '👃🏽', color: 'bg-orange-200', rhyme: " What do we smell with?\n Nose" },
        { word: 'Legs', emoji: '🦵', color: 'bg-green-100', rhyme: " What do we do with our legs?\n Walk" },
        { word: 'Tongue', emoji: '👅', color: 'bg-red-100', rhyme: " What do we taste with?\n Tongue" },
        { word: 'Brain', emoji: '🧠', color: 'bg-pink-300', rhyme: " What do we do with our brain?\n Think" },
        { word: 'Teeth', emoji: '😁', color: 'bg-gray-200', rhyme: " What do we chew with?\n Teeth" },
        { word: 'Heart', emoji: '❤️', color: 'bg-red-300', rhyme: " What does our heart do?\n Pump" },
        { word: 'Hands', emoji: '✍️', color: 'bg-yellow-100', rhyme: " What do we write with?\n Hands" },
        { word: 'Mouth', emoji: '👄', color: 'bg-rose-200', rhyme: " What do we do with our mouth?\n Eat" }
    ],
    colorsShapes: [
        { word: 'Red', emoji: '🔴', color: 'bg-red-500', textClass: 'text-white' },
        { word: 'Triangle', emoji: '🔺', color: 'bg-blue-200' }
    ],
    magicWords: [
        { word: 'Please', emoji: '🙏', desc: 'When we ask for something \nExample: “Please give me a toy.”', color: 'bg-pink-200' },
        { word: 'Thank You', emoji: '💖', desc: 'When someone helps us \nExample: “Thank you for the gift.”', color: 'bg-blue-200' },
        { word: 'Sorry', emoji: '😔', desc: 'Use when we hurt someone or make a mistake. \nExample:Sorry, I pushed you.', color: 'bg-blue-200' }
    ],
    flowers: [
        { word: 'Smell', emoji: '👃', color: 'bg-pink-200', rhyme: " What smell do flowers have?\n Sweet" },
        { word: 'Bees', emoji: '🐝', color: 'bg-yellow-200', rhyme: " What do bees collect from flowers?\n Nectar" },
        { word: 'Butterflies', emoji: '🦋', color: 'bg-blue-200', rhyme: " What do butterflies drink from flowers?\n Nectar" },
        { word: 'Perfume', emoji: '🧴', color: 'bg-purple-200', rhyme: " What are flowers used to make?\n Perfume" },
        { word: 'Ittar', emoji: '🧪', color: 'bg-rose-200', rhyme: " What else are flowers used to make?\n Ittar" },
        { word: 'Bouquet', emoji: '💐', color: 'bg-green-200', rhyme: " What do we give on birthdays?\n Bouquet" },
        { word: 'Grow', emoji: '🌱', color: 'bg-emerald-200', rhyme: " Where do flowers grow?\n Plants" },
        { word: 'Water', emoji: '💧', color: 'bg-cyan-200', rhyme: " What do flowers need to grow?\n Water" },
        { word: 'Colours', emoji: '🎨', color: 'bg-orange-200', rhyme: " What colour can a flower be?\n Red, Green, Yellow and white" },
        { word: 'Lotus', emoji: '🪷', color: 'bg-pink-300', rhyme: " Which is the national flower of India?\n Lotus" },
        { word: 'Rose', emoji: '🌹', color: 'bg-red-300', rhyme: " Which is the King of Flowers?\n Rose" },
        { word: 'Fruit', emoji: '🍎', color: 'bg-lime-200', rhyme: " What do flowers become after blooming?\n Fruit" }
    ],
    german: [
        { word: 'Hallo', emoji: '👋', color: 'bg-blue-200', rhyme: "Hello - Hallo" },
        { word: 'Guten Morgen', emoji: '🌅', color: 'bg-orange-200', rhyme: "Good Morning - Guten Morgen" },
        { word: 'Guten Tag', emoji: '☀️', color: 'bg-yellow-200', rhyme: "Good Afternoon - Guten Tag" },
        { word: 'Guten Abend', emoji: '🌇', color: 'bg-red-200', rhyme: "Good Evening - Guten Abend" },
        { word: 'Gute Nacht', emoji: '🌙', color: 'bg-indigo-200', rhyme: "Good Night - Gute Nacht" },
        { word: 'Montag', emoji: '📅', color: 'bg-purple-200', rhyme: "Monday - Montag" },
        { word: 'Dienstag', emoji: '🗓️', color: 'bg-pink-200', rhyme: "Tuesday - Dienstag" },
        { word: 'Mittwoch', emoji: '🐪', color: 'bg-amber-200', rhyme: "Wednesday - Mittwoch" },
        { word: 'Donnerstag', emoji: '⛈️', color: 'bg-cyan-200', rhyme: "Thursday - Donnerstag" },
        { word: 'Freitag', emoji: '🎉', color: 'bg-emerald-200', rhyme: "Friday - Freitag" },
        { word: 'Samstag', emoji: '🎈', color: 'bg-rose-200', rhyme: "Saturday - Samstag" },
        { word: 'Sonntag', emoji: '☀️', color: 'bg-yellow-300', rhyme: "Sunday - Sonntag" }
    ],
    flagsCars: [
        // Car Logos
        { word: 'BMW', image: 'src/bmw.png', color: 'bg-blue-200', rhyme: "Car Logo: BMW" },
        { word: 'Mercedes-Benz', image: 'src/mercedes.png', color: 'bg-gray-300', rhyme: "Car Logo: Mercedes-Benz" },
        { word: 'Audi', image: 'src/audi.png', color: 'bg-red-200', rhyme: "Car Logo: Audi" },
        
        // Flags
        { word: 'India', image: 'src/Indipng', color: 'bg-orange-200', rhyme: "Flag of India" },
        { word: 'Sri Lanka', image: 'src/Sri_Lankpng', color: 'bg-yellow-200', rhyme: "Flag of Sri Lanka" },
        { word: 'USA', image: 'src/uspng', color: 'bg-blue-300', rhyme: "Flag of USA" },
        { word: 'UK', image: 'src/uk.png', color: 'bg-red-300', rhyme: "Flag of UK" },
        { word: 'Turkey', image: 'src/turkey.png', color: 'bg-rose-300', rhyme: "Flag of Turkey" }
    ],
};

// Rhymes structured by books
// Rhymes structured by books with Emojis and Colors restored!
const rhymesData = {
    morningRhymes: [
        { word: 'Jana Gana Mana', emoji: '🇮🇳', color: 'bg-orange-200', rhyme: "Jana-Gana-Mana-Adhinayaka, Jaya He\nBharat-Bhagya-Vidhata,\nPunjab-Sindhu-Gujurata-Maratha-Dravid-Utkala-Banga\nVidhya-Himachala-Yamuna-Ganga Ucchala-Jaladhi Taranga\nTava Subha Naame Jage, Tava Shubh Ashisha Mage,\nGahe Tava Jaya Gath\nJana-Gana-Mangala Dayaka, Jaya He,\nBharat-Bhagya-Vidhata,\nJaya He, Jaya He, Jaya He, Jaya Jaya Jaya, Jaya He." },
        { word: 'Good Morning', emoji: '🌅', color: 'bg-yellow-200', rhyme: "Good morning, Good morning, Good morning to you,\nGood morning to all of you.\nWe are all in our place, with sweet smiling faces.\nThis is the way we start a new day,\nSo good morning to all of you." },
        { word: 'Ham Honge Kaamyab', emoji: '🕊️', color: 'bg-blue-200', rhyme: "Honge kaamyab, Honge kaamyab,\nHam honge kaamyab ek din\nHo ho mann mai hai vishwaas, pura hai vishwaas\nHam honge kaamyab ek din.\n\nHogee shantee chaaro aur\nek din,\nHo ho mann mai hai vishwaas, pura hai vishwaas\nHogee shantee chaaro aur ek din.\n\nHam chaalenge saath saath, dale haatho me haath\nHam chaalenge saath saath ek din,\nHo ho mann mai hai vishwaas, pura hai vishwaas\nHam chaalenge saath saath ek din." },
        { word: 'Snack Time Prayer', emoji: '🥪', color: 'bg-green-200', rhyme: "Thank you for the world so sweet,\nThank you for the food we eat,\nThank you for the birds that sing,\nThank you for everything." },
        { word: 'Mulberry Bush', emoji: '🌳', color: 'bg-teal-200', rhyme: "Here we go round the mulberry bush\nThe mulberry bush, the mulberry bush,\nHere we go round the mulberry bush,\nOn a cold and frosty morning\n\nThis is the way we wash our hands,\nWash our hands, wash our hands,\nThis is the way we wash our hands,\nOn a cold and frosty morning\n\n(Continue with-) This is the way we wash our face,\nThis is the way we take a bath,\nThis is the way we put on our clothes,\nThis is the way we eat our food,\nThis is the way we go to school." },
        { word: 'I Love You', emoji: '💖', color: 'bg-pink-200', rhyme: "I love you in the evening, And underneath the moon.\nOh, skinamarink a-dink, a-dink.\nSkinamarink a-doo.\nI love you.\n\nI love you, you love me\nWe all are a happy family,\nWith a great big hug, and kiss from me to you.\nWon't you say you love me too?\nLove you papa, love you mama\nLove you brother and sister too.\nWith a great big hug, and kiss from me to you,\nWon't you say you love me too?\nI LOVE YOU." },
        { word: "God's Love", emoji: '✨', color: 'bg-purple-200', rhyme: "God’s love to me is so wonderful (-3x)\nOh oh! Wonderful love\nIt’s so high you can’t get over it,\nIt’s so deep you can’t get under it,\nIt’s so wide you can’t get around it,\nOh oh! Wonderful love\nHigher, higher than the mountains,\nDeeper, deeper than the ocean,\nWider, wider than the universe,\nOh oh! Wonderful love." },
        { word: 'I Am Waiting', emoji: '⏳', color: 'bg-indigo-200', rhyme: "I am waiting, I am waiting,\nJust for ____ , just for ____,\nShow me that you’re ready,\nShow me that you’re ready,\n1, 2, 3 – eyes on me!\n1, 2, 3 – looking at me!\n1, 2, 3 – smiling at me" },
        { word: 'Super Manners', emoji: '🦸', color: 'bg-red-200', rhyme: "Special special special me\nHow I wonder what I’ll be\nIn this big world I can be\nAnything I want to be\nSpecial special special me." },
        { word: 'Aaj Somwar Hai', emoji: '🐭', color: 'bg-orange-300', rhyme: "Aaj somwar hai (2x)\nKisko bukhar hai (2x)\nChuhe ko bukhar hai (2x)\nChuha gaya doctor ke paas,\nDoctor ne mari sui,\nChuha Roya ooyi ooyi." },
        { word: 'Togetherness', emoji: '🫂', color: 'bg-yellow-300', rhyme: "The more we get together,\nTogether, Together,\nThe more we get together,\nThe happier we'll be.\nFor your friends are my friends,\nAnd my friends are your friends,\nThe more we get together\nThe happier we'll be." },
        { word: 'I Am Special', emoji: '🌟', color: 'bg-sky-200', rhyme: "I am special, I am special\nIf you look, you will see\nSomeone very special, very special\nThat’s me, that’s me." },
        { word: 'I Am Confident', emoji: '💪', color: 'bg-lime-200', rhyme: "I am confident, I am confident\nIf you look, you will see\nSomeone very confident, very confident\nThat’s me, that’s me.\n\n(Continue with kind, strong, bold, caring beautiful)" },
        { word: 'Hello, How Are You?', emoji: '👋', color: 'bg-amber-200', rhyme: "Hello, hello, how are you? (3x)\nHow are you today?\nI am fine, I am great, (3x)\nI’m very well today." },
        { word: 'Happy Days', emoji: '😊', color: 'bg-rose-200', rhyme: "This is the way we start our day,\nStart our day, start our day,\nThis is the way we start our day,\nSo early in the morning,\nFirst we smile and say hello,\nSo hello, so hello,\nFirst we smile and say hello,\nSo early in the morning,\nThen we sit down quietly, quietly, quietly,\nThen we sit down quietly,\nSo early in the morning,\nWe will listen carefully, carefully, carefully,\nWe will listen carefully,\nSo early in the morning." },
        { word: 'Days of the Week', emoji: '📅', color: 'bg-cyan-200', rhyme: "Monday Tuesday (clap 3x)\nWednesday Thursday (tap 3x)\nFriday,\nAlmost done!\nSaturday Sunday is so much fun.\nNow we know the days of the week!\nClap your hands, (3x)\nStomp your feet. (3x)" },
        { word: 'Months of the Year', emoji: '🗓️', color: 'bg-fuchsia-200', rhyme: "January's cold, with winter's chill,\nFebruary's love, with hearts that thrill.\nMarch arrives, with winds so bold,\nApril showers, bring May's flowers to hold.\nJune is summer, warm and bright,\nJuly's fireworks, on a starry night.\nAugust's end, of summer's fun,\nSeptember's back, to school for everyone.\nOctober's Halloween, with costumes so fine,\nNovember's thanks, for family and dine.\nDecember's snow, with Christmas cheer,\nTwelve months pass, and a new year draws near." },
        { word: 'I Can Do Anything', emoji: '🚀', color: 'bg-violet-200', rhyme: "I am strong, I am kind, I am powerful,\nI am brave, I am free, I am helpful,\nWith love in my heart and smile on my face,\nI can handle anything, anytime, anyplace." },
        { word: 'Itni Shakti Hame', emoji: '🙏', color: 'bg-emerald-200', rhyme: "Itani shakti hame dena daata\nMaan ka vishwaas kamazor ho na (2x)\nHum chalem nek raste pe humse,\nBhuulakar bhee koyi bhool ho naa\nItani shakti hamen dena daata\nMaan ka vishwaas kamazor ho na\n\nDur agyaan ke hon andhere\nTu hamein gyaan kee roshni de. (2x)\nHar buraai se bachate rahen hum\nJitni bhee de, bhalee zindagi de\nBair ho naa kisi ka kisi se\nBhaavana man mein badle kee ho naa\nHum chalem nek raste pe humse\nBhuulakar bhee koyi bhool ho naa,\nItani shakti hamen dena daata\nMaan ka vishwaas kamazor ho na" },
        { word: 'I Am Brave', emoji: '🦁', color: 'bg-orange-200', rhyme: "I am brave (2x)\nIf you look, you will see,\nSomeone’s very brave (2x)\nThat is me. (2x)" },
        { word: 'Roll The Dough', emoji: '🥯', color: 'bg-amber-300', rhyme: "Roll, roll, roll the dough,\nRoll it on the table,\nRoll, roll, roll the dough,\nRoll it if you are able.\n\nPat, pat, pat, the dough,\nPat it on the table,\nPat, pat, pat, the dough,\nPat it if you are able.\n\nPoke, poke, poke the dough,\nPoke it on the table,\nPoke, poke, poke the dough,\nPoke it if you are able.\n\nPinch, pinch, pinch the dough,\nPinch it on the table,\nPinch, pinch, pinch the dough,\nPinch it if you are able.\n\nStretch, stretch, stretch the dough..." }
    ],
    book1: [
        { word: 'A - Ants', emoji: '🐜', color: 'bg-red-200', rhyme: "Ants on my arm, ah ah ah,\nAnts on my arm,\nThey're causing me alarm." },
        { word: 'B - Bat', emoji: '🦇', color: 'bg-blue-200', rhyme: "Bring your bat and bring your ball,\nbuh buh buh,\nBring your bat and bring your ball,\nTo the park to play!" },
        { word: 'C - Castanets', emoji: '🪇', color: 'bg-green-200', rhyme: "We are clicking castanets,\ncuh cuh cuh,\nWe are clicking castanets,\ncuh cuh cuh,\nWe are clicking castanets,\nClicking castanets,\ncuh cuh cuh" },
        { word: 'D - Drum', emoji: '🥁', color: 'bg-yellow-200', rhyme: "See me play upon my drum,\nPlaying drums is lots of fun!\nWith a duh duh duh duh duh duh duh,\nSee me play upon my drum." },
        { word: 'Aalu Kachhalu', emoji: '🥔', color: 'bg-orange-200', rhyme: "Aalu kachhalu, kahan gaye the\nBaigan ki tokri mein so rahe the\nBaigan ne Dhaka mara, ro rahe the\nMummy ne pyaar kiya has rahe the." },
        { word: 'My Garden', emoji: '🌷', color: 'bg-pink-200', rhyme: "Tulips sway, in the gentle breeze,\nTheir cups shaped, like royal ease.\nIn colors bright, they bloom with glee,\nA beautiful sight, for you and me." },
        { word: 'Veggie Snacks', emoji: '🥦', color: 'bg-green-300', rhyme: "Carrots, peas and broccoli,\nVegetables are good for me.\nFor my snack and in my lunch,\nVeggie sticks are great to munch!\nCarrots, peas and broccoli,\nVegetables are good for me." },
        { word: 'Five Fat Peas', emoji: '🫛', color: 'bg-emerald-200', rhyme: "Five fat peas in a pea pod pressed,\nOne grew, two grew, and so did the rest.\nThey grew and they grew and they grew so fat,\nThey grew so fat that the pea pod popped!" },
        { word: 'Blooming Flowers', emoji: '🌻', color: 'bg-yellow-300', rhyme: "Roses are red, violets are blue,\nA beautiful garden, waiting for you.\nTulips sway, in the breeze so light,\nA colorful sight, a pure delight.\nDaisies dance, with petals so bright,\nA happy flower, shining with delight.\nSunflowers tall, with faces so bold,\nFollowing the sun, with stories untold.\nRoses bloom, in the garden so fair,\nPetals unfolding, with a sweet scent to share.\nTulips sway, in the breeze so light,\nDaisies dance, with joy so bright.\nSunflowers tall, with faces so bold,\nA colorful garden, to behold." },
        { word: 'Number Rumba', emoji: '🔢', color: 'bg-indigo-200', rhyme: "Let's do the Number Rumba! Let's do the Number Rumba!\nThe Number Rumba all day long!\nNumber 1, Number 1\nNumber 1 is straight and fun!\nNumber 2, Number 2\nTwo kangaroos in the zoo!\nNumber 3, Number 3\nThree apples on a tree!\nNumber 4, Number 4\nFour children on the floor!\nNumber 5, Number 5\nFive bees in the hive!\nNumber 6, Number 6\nSix people picking up sticks!\nNumber 7, Number 7\nSeven people peeping from the heavens!\nNumber 8, Number 8\nEight people standing at the gate!\nNumber 9, Number 9\nNumber 9, I am fine!\nNumber 10, Number 10\nTen, there is a big fat hen!\nLet's do the Number Rumba! Let's do the Number Rumba!\nThe Number Rumba all day long!" },
        { word: 'Buckle My Shoe', emoji: '👞', color: 'bg-amber-200', rhyme: "One, two, buckle my shoe,\nThree, four, shut the door,\nFive, six, pick up sticks,\nSeven, eight, lay them straight,\nNine, ten, a big fat hen!" },
        { word: 'Action Rhyme', emoji: '🏃', color: 'bg-cyan-200', rhyme: "Hop a little, jump a little,\n1, 2, 3!\nRun a little, skip a little,\nTap one knee!\nBend a little, stretch a little,\nTouch your head!\nYawn a little, sleep a little,\nIn your bed!" },
        { word: 'Bubble Gum', emoji: '🍬', color: 'bg-pink-300', rhyme: "Icky, sticky, icky, sticky bubble gum,\nBubble gum, bubble gum.\nIcky, sticky, icky, sticky bubble gum,\nMakes your hands stick to your nose!\nAnd you pull them, and you pull them,\nAnd you pull them away!" },
        { word: 'My Eyes', emoji: '👀', color: 'bg-blue-100', rhyme: "What are my eyes for?\nWhat are my eyes for?\nCan you tell? Can you tell?\nMy eyes are to see with,\nJust to see with.\nRat-a-tat-tat! Rat-a-tat-tat!" },
        { word: 'My Ears', emoji: '👂', color: 'bg-orange-100', rhyme: "What are my ears for?\nWhat are my ears for?\nCan you tell? Can you tell?\nMy ears are to hear with,\nJust to hear with.\nRat-a-tat-tat! Rat-a-tat-tat!" },
        { word: 'My Nose', emoji: '👃', color: 'bg-rose-100', rhyme: "What is my nose for?\nWhat is my nose for?\nCan you tell? Can you tell?\nMy nose is to smell with,\nJust to smell with.\nRat-a-tat-tat! Rat-a-tat-tat!" },
        { word: 'Body Parts', emoji: '👤', color: 'bg-teal-100', rhyme: "Look at my eyes,\nI have two!\nLook at my ears,\nI have two!\nLook at my hands,\nI have two!\nLook at my legs,\nI have two!\nCock-a-doodle-doo!\nCock-a-doodle-doo!" },
        { word: 'Mummy & Daddy', emoji: '👪', color: 'bg-red-100', rhyme: "Mummy darling, Daddy darling,\nI love you, I love you!\nSee your baby dancing,\nSee your baby dancing,\nJust for you! Just for you!" },
        { word: 'Finger Family', emoji: '🖐', color: 'bg-purple-200', rhyme: "Daddy finger, daddy finger,\nWhere are you?\nHere I am, here I am,\nHow do you do?\nMommy finger, mommy finger,\nWhere are you?\nHere I am, here I am,\nHow do you do?\nBrother finger, brother finger,\nWhere are you?\nHere I am, here I am,\nHow do you do?\nSister finger, sister finger,\nWhere are you?\nHere I am, here I am,\nHow do you do?\nBaby finger, baby finger,\nWhere are you?\nHere I am, here I am,\nHow do you do?" },
        { word: 'Make a Circle', emoji: '⭕', color: 'bg-indigo-300', rhyme: "Make a circle,\nBig, big, big!\nSmall, small, small!\nBig, big, big!\nMake a circle,\nBig, big, big!\nSmall, small, small!\nMake a circle,\nUp, up, up!\nDown, down, down!\nUp, up, up!\nMake a circle,\nUp, up, up!\nNow stand up!" },
        { word: 'I Am Special', emoji: '🌟', color: 'bg-yellow-200', rhyme: "I am special,\nI am smart.\nI am very happy.\nI am brave,\nI am strong.\nI love myself with all my heart." },
        { word: 'Seven Days', emoji: '📅', color: 'bg-sky-200', rhyme: "There are seven days,\nThere are seven days,\nThere are seven days in a week.\nMonday, Tuesday, Wednesday,\nThursday, Friday,\nSaturday, Sunday.\nSaturday and Sunday are holidays,\nWe stay home and we play.\nWe come back to school on Monday,\nMonday, Tuesday, Wednesday,\nThursday, Friday.\nSaturday... oops!\nSaturday and Sunday are holidays!" },
        { word: 'Days Chant', emoji: '🗓️', color: 'bg-fuchsia-200', rhyme: "Mon, Mon, Monday!\nTue, Tue, Tuesday!\nWed, Wed, Wednesday!\nThu, Thu, Thursday!\nFri, Fri, Friday!\nSat, Sat, Saturday!\nSun, Sun, Sunday!\nSaturday and Sunday are holidays!" },
        { word: 'Guru Mantra', emoji: '🧑‍🏫', color: 'bg-rose-100', rhyme: "Gurur Brahma Gurur Vishnu \nGurur Devo Maheshwarah \nGuruh Sakshat Parabrahma \nTasmai Shri Gurave Namah" }
    ],
    book2: [
        { word: 'One Finger', emoji: '👆', color: 'bg-red-200', rhyme: "One finger, one finger turn turn turn,\nTurn into a worm,\nCrawl, crawl, crawl.\nTwo finger, Two finger turn turn turn,\nTurn into a bunny,\nHop, hop, hop.\nThree finger, three finger turn turn turn,\nTurn into a cat,\nMeow, meow, meow.\nFour finger, four finger turn turn turn,\nTurn into a butterfly,\nFly, fly, fly.\nFive finger, five finger turn turn turn,\nTurn into a lion,\nRoar, roar, roar." },
        { word: 'Pat A Cake', emoji: '🍰', color: 'bg-orange-200', rhyme: "Pat a cake, pat a cake baker’s man\nBake me a cake as fast as you can\nPat it and prick it and\nMark it with B.\nPut it in the oven for baby and me." },
        { word: 'Dhobi Aaya', emoji: '👕', color: 'bg-blue-200', rhyme: "Dhobi aaya, dhobi aaya\nKapde saaf, kapde saaf\nKitne kapde laaya,\nKitne kapde laaya,\n1…2…3…\n4…5…6…\n7…8…9…10…bus!" },
        { word: 'The Postman', emoji: '📫', color: 'bg-yellow-200', rhyme: "Postman aaya,\nPostman aaya,\nKitni chitti laya,\nKitni chitti laya,\n1…2…3…\n4…5…6…\n7…8…9…10…bus!" },
        { word: 'Police Officer', emoji: '👮', color: 'bg-indigo-200', rhyme: "I’m a police officer\nWith my star,\nI help people\nNear and far.\nIf you have a problem,\nCall on me,\nAnd I will be there, 1, 2, 3!" },
        { word: 'Carpenter Tools', emoji: '🔨', color: 'bg-amber-200', rhyme: "The carpenter with his hammer goes\nBang, bang, bang, (3x)\nAll day long.\nCarpenter with his saw goes,\nSee, saw, see, (3 x)\nAll day long." },
        { word: "Cobbler's Song", emoji: '👞', color: 'bg-stone-200', rhyme: "Cobbler cobbler mend my shoe,\nGet it done by half past 2.\nStitch it up and stitch it down,\nAnd I will give you half a crown." },
        { word: 'The Doctor', emoji: '👨‍⚕️', color: 'bg-teal-200', rhyme: "The doctor makes us well, the doctor makes us well\nHey! Ho! What do you know?\nThe doctor makes us well." },
        { word: 'Firefighter', emoji: '🚒', color: 'bg-red-300', rhyme: "I’m a little firefighter on the go.\nHere is my helmet, here is my hose.\nWhen I see a fire, hear me shout:\n“Turn on the water and put the fire out!”" },
        { word: 'Hot Cross Buns', emoji: '🥐', color: 'bg-orange-300', rhyme: "Hot cross buns, hot cross buns\nOne a penny, two a penny\nHot cross buns\nIf you have no daughters,\nGive them to your sons.\nOne a penny, two a penny\nHot cross buns." },
        { word: 'Teachers', emoji: '👩‍🏫', color: 'bg-emerald-200', rhyme: "One teacher comes to a school each day,\nSchool each day, school each day.\nOne teacher comes to a school each day,\nTo help us learn and grow.\nShe smiles and helps us learn all day.\nLearn all day, learn all day.\nShe smiles and helps us learn all day\nWe are glad we come to school." },
        { word: 'Chubby Cheeks', emoji: '👶', color: 'bg-pink-200', rhyme: "Chubby cheeks, dimple chin\nRosy lips, teeth within,\nCurly hair, very fair,\nEyes are blue lovely too,\nTeachers pet is that you?\nYes yes yes." },
        { word: 'Head & Shoulders', emoji: '🧍', color: 'bg-cyan-200', rhyme: "Head and shoulders knees and toes,\nKnees and toes knees and toes.\nHead and shoulders knees and toes\nEyes ears mouth and nose. (2x)\n\nMarch, march, march,\nLet’s all march\nMarch, march, march,\nGet your bodies charged.\n\nJump, jump, jump,\nLet’s all jump,\nJump, jump, jump,\nMake your muscles pump.\n\nPunch, punch, punch,\nLet’s all punch,\nPunch, punch, punch,\nHave a hearty munch." },
        { word: 'Where is Thumbkin', emoji: '👍', color: 'bg-purple-200', rhyme: "Where is thumbkin (-2x)\nHere I am (-2x)\nHow are you this morning?\nVery well thank you\nRun away (-2x)\n\n(Continue with: Pointer, Tall man, Ring man and Baby)" },
        { word: 'Five Senses', emoji: '👁️', color: 'bg-rose-200', rhyme: "Five senses, five senses\nWe have them, we have them\nSeeing, hearing, touching, tasting and smiling\nThere are five, there are five" },
        { word: 'Open & Shut', emoji: '👐', color: 'bg-yellow-300', rhyme: "Open them, shut them (2x)\nGive a little clap,\nOpen them, shut them (2x)\nLay them on your lap.\nCreep them, creep them, creep them\nRight up to your chin\nOpen up you little mouth, but do not put them in." },
        { word: 'To The Market', emoji: '🛒', color: 'bg-lime-200', rhyme: "We are going to the market\nWe are going to the fair,\nTo see a senorita,\nWith flowers on her hair.\nOh! Shaky, shaky, shaky\nShake as you can,\nShake it as a milkshake,\nAnd do the best you can\nOh! Rumble to the bottom,\nAnd rumble to the top,\nTurn around and turn around,\nTill you make a stop." },
        { word: 'Fingers Up', emoji: '🙌', color: 'bg-fuchsia-200', rhyme: "Dance your fingers up, dance your fingers down.\nDance your fingers to the side, dance them all around.\nDance them on your shoulders, dance them on your head\nDance them on your tummy, and put them all to bed." },
        { word: 'Here We Go', emoji: '🚶', color: 'bg-sky-200', rhyme: "Here we go - up, up, up.\nHere we go - down, down, down.\nHere we go - moving forward\nHere we go – moving backward\nHere we go round and round and round\nNow, Here we all sit right down." },
        { word: 'If You Are Happy', emoji: '😊', color: 'bg-amber-300', rhyme: "If you are happy happy and you know it, wiggle wiggle\nIf you are happy happy and you know it, wiggle wiggle\nIf you are happy happy and you know it,\nThen your face will surely show it.\nIf you are happy happy and you know it, wiggle wiggle\nWhat rhymes with wiggle? Jiggle!\nIf you are happy happy and you know it, jiggle jiggle." },
        { word: 'Hop A Little', emoji: '🦘', color: 'bg-teal-300', rhyme: "Hop a little, jump a little,\nOne-two-three,\nRun a little, skip a little,\nTap one knee,\nBend a little, stretch a little,\nNod your head,\nYawn a little, sleep a little,\nIn your bed." },
        { word: 'Ten Little Fingers', emoji: '🤲', color: 'bg-violet-200', rhyme: "I have ten little fingers, they all belong to me!\nI can make them do things- would you like to see?\nI can squeeze them tight, I can open them wide,\nI can clap them together, I can make them hide,\nI can shake them up high, I can shake them down low\nI can fold them together like so!\nI have ten little fingers, they all belong to me.\nDo you have 10 fingers?\nLet’s count and see! 1, 2, 3, 4, 5, 6, 7, 8, 9, 10!" },
        { word: 'My Body Parts', emoji: '💪', color: 'bg-red-200', rhyme: "My arms are for hugging, I love you,\nMy eyes are for seeing, peekaboo,\nMy ears are for hearing, what did you say?\nMy mouth is for talking and singing all day,\nMy tongue is for tasting yum yum yum,\nMy teeth are for chewing gum gum gum,\nMy fingers are for counting 1, 2, 3..\nThank you for saying this song with me." },
        { word: 'Green (Twinkle)', emoji: '🌿', color: 'bg-green-400', textClass: 'text-white', rhyme: "Green, green, what a sight,\nGreen leaves dancing in the light.\nGreen grass soft below my feet,\nGreen peas are fun to eat!\nGreen, green, everywhere,\nNature's beauty we all share!" },
        { word: 'Triangle', emoji: '🔺', color: 'bg-blue-300', rhyme: "Make a triangle, make a triangle,\nWith your hands, with your hands.\nThree straight sides, three straight sides,\nThree corners, three corners." },
        { word: 'White', emoji: '☁️', color: 'bg-white', rhyme: "White is lovely,\nWhite is lovely,\nLook around,\nLook around.\nClouds and milk are white,\nStars shine big and bright,\nWhat a sight,\nWhat a delight!" },
        { word: 'Perfect Posture', emoji: '🧍', color: 'bg-indigo-300', rhyme: "Perfect posture, perfect posture,\nMind your back, mind your back,\nGrow up to be pretty,\nGrow up to be handsome,\nDo not slouch, do not slouch." },
        { word: 'Big and Small', emoji: '🐘', color: 'bg-gray-300', rhyme: "Big, big, big, big,\nBig, big, big the ball.\nSmall, small, small, small,\nSmall, small, small the ball.\nBig and small,\nWe know them all!" },
        { word: 'Gayatri Mantra', emoji: '🕉️', color: 'bg-orange-400', textClass: 'text-white', rhyme: "Om Bhur Bhuvah Swaha\nTat Savitur Varenyam\nBhargo Devasya Dheemahi\nDhiyo Yo Nah Prachodayat" }
    ],
    book3: [
        { word: 'Little Bird', emoji: '🐦', color: 'bg-blue-200', rhyme: "Once I saw a little bird\nCome hop, hop, hop;\nSo I cried “ little bird will you stop, stop, stop?”\nAnd was going to the window\nTo say “how do you do?”\nBut he shook his little tail,\nAnd far away flew." },
        { word: 'Chi Chi Chu Chu', emoji: '🐤', color: 'bg-yellow-200', rhyme: "Chi chi chu chu karte chidiya,\nPhur phur udate chidiya,\nPhudak phudak kar gaana gaate chidiya,\nRoz subh mujhe uthati chidiy" },
        { word: 'Dickie Birds', emoji: '🕊️', color: 'bg-stone-200', rhyme: "Two little dickie birds,\nSitting on a wall,\nOne names Peter,\nOne named Paul,\nFly away Peter,\nFly away Paul,\nCome back Peter,\nCome back Paul." },
        { word: 'Bagiya Mein Mor', emoji: '🦚', color: 'bg-emerald-200', rhyme: "Chhip chhip dekho\nKaro na shor,\nDhikaee padate badal,\nPankh pasaro nache mor." },
        { word: 'Birds', emoji: '🦜', color: 'bg-green-200', rhyme: "Parrots are green and sparrows are brown,\nPigeons are grey and they fly around,\nCrows are so black, as black as you can be.\nPeacock is colourful, birds as you can see.\nBirds have feathers, tails and beak,\nSeeds and worms are a great big treat,\nThey flap their wings and fly around,\nHigher and higher off the ground." },
        { word: 'Five Little Ducks', emoji: '🦆', color: 'bg-orange-200', rhyme: "Five little ducks\nWent swimming one day,\nOver the hills\nAnd far away.\nMother duck said,\n“Quack, quack, quack, quack!”\nBut only four little ducks\nCame swimming back.\n(Continue with 4, 3, 2, 1 and finally “Five little ducks came swimming back.”)" },
        { word: 'Cock-a-Doodle-Doo', emoji: '🐓', color: 'bg-red-200', rhyme: "Cock-a-doodle-doo!\nMy dame has lost her shoe.\nMy master's lost his fiddle stick,\nAnd knows not what to do." },
        { word: 'Three Little Birds', emoji: '🔢', color: 'bg-indigo-200', rhyme: "One little, two little, three little birds,\nFour little, five little, six little birds,\nSeven little, eight little, nine little birds,\nTen little birds!\nTen little birds sitting in a tree,\nTen little birds looking at me.\nFlap their wings and fly away,\nCome back, little birds, another day!" },
        { word: 'Robin Redbreast', emoji: '🪶', color: 'bg-rose-200', rhyme: "Little Robin Redbreast\nSat upon a tree,\nUp went the little bird,\nAnd away flew he.\nDown came Robin\nAnd hopped upon the ground,\nLooking for some little worms\nThat he could find around." },
        { word: 'Five Little Birds', emoji: '🐦‍⬛', color: 'bg-slate-200', rhyme: "Five little birds\nSitting in a tree,\nOne flew away\nAnd then there were four.\nFour little birds\nSitting in a tree,\nOne flew away\nAnd then there were three.\n(Continue until one, then “One little bird… flew away, and then there were none!”)" },
        { word: 'Chidiya Rani', emoji: '💤', color: 'bg-purple-200', rhyme: "चिच़िया रानी सोई है,\nमीठे सपने खोई है।\nसूरज दादा आए हैं,\nचिरणें साथ में लाए हैं।\nचिच़िया रानी उठ जाओ,\nपंख अपने फैलाओ।\nिू ूँ-िू ूँ िरिे गाना गाओ,\nउ़ििर आसमान में जाओ।" },
        { word: 'Letter i', emoji: '🖋️', color: 'bg-cyan-200', rhyme: "Inky the mouse is my pet,\nShe spilled the ink and got wet.\nThe ink it ran down to her feet,\nAnd Inky got ink all over her seat." },
        { word: 'Letter j', emoji: '🍮', color: 'bg-pink-200', rhyme: "Jolly, jolly, jelly,\nJelly on a plate.\nJelly, jelly, jelly,\nJelly tastes great!" },
        { word: 'Letter k', emoji: '⚽', color: 'bg-lime-200', rhyme: "Kicking and catching,\nKicking and catching,\nKick the ball,\nCatch the ball." },
        { word: 'Letter L', emoji: '🦁', color: 'bg-amber-200', rhyme: "Look at the lion,\nHe likes to lick.\nLook at the lion,\nHe likes to lick." },
        { word: 'Rectangle', emoji: '🟦', color: 'bg-blue-300', rhyme: "Rectangle, rectangle,\nLong and wide,\nFour little corners\nSide by side!" },
        { word: 'Open and Close', emoji: '👐', color: 'bg-yellow-300', rhyme: "Open, open, open wide,\nClose, close, close it tight.\nOpen and close,\nMorning to night!" },
        { word: 'Colour Red', emoji: '🍎', color: 'bg-red-300', rhyme: "Red, red, lovely red,\nRed is the colour of an apple.\nRed is bright, red is fun,\nRed is the colour of the shining sun!" },
        { word: 'Number 4', emoji: '🌟', color: 'bg-sky-200', rhyme: "Four little stars up in the sky,\nTwinkle, twinkle, way up high.\nFour little stars, 1, 2, 3, 4,\nShining brightly forevermore!" },
        { word: 'If You’re Happy', emoji: '👏', color: 'bg-teal-200', rhyme: "If you’re happy and you know it, clap your hands,\nIf you’re happy and you know it, clap your hands,\nIf you’re happy and you know it,\nAnd you really want to show it,\nIf you’re happy and you know it, clap your hands.\n\nIf you’re sad and you know it, wipe your tears,\nIf you’re angry and you know it, stamp your feet,\nIf you’re scared and you know it, hold my hand,\nIf you’re surprised and you know it, say “Oh!”" },
        { word: 'Gayatri Mantra', emoji: '🕉️', color: 'bg-orange-300', rhyme: "Om Bhur Bhuvah Swaha\nTat Savitur Varenyam\nBhargo Devasya Dheemahi\nDhiyo Yo Nah Prachodayat" },
        { word: 'Twameva Mata', emoji: '🙏', color: 'bg-rose-300', rhyme: "Twameva Mata Cha Pita Twameva\nTwameva Bandhush Cha Sakha Twameva\nTwameva Vidya Dravinam Twameva\nTwameva Sarvam Mama Deva Deva" }
    ]
};

const categories = [
    { id: 'alphabets', title: 'A B C', icon: '🔤', color: 'bg-pink-400' },
    { id: 'numbers', title: '1 2 3', icon: '🔢', color: 'bg-blue-400' },
    { id: 'colorsShapes', title: 'Colors & Shapes', icon: '🎨', color: 'bg-yellow-400' },
    { id: 'bodySenses', title: 'My Body', icon: '👤', color: 'bg-green-400' },
    { id: 'vegetables', title: 'Veggies', icon: '🥕', color: 'bg-orange-400' },
    { id: 'birds', title: 'Birds', icon: '🐦', color: 'bg-cyan-400' },
    { id: 'helpers', title: 'Helpers', icon: '👮', color: 'bg-purple-400' },
    { id: 'magicWords', title: 'Magic Words', icon: '✨', color: 'bg-rose-400' },
    { id: 'flowers', title: 'Flowers', icon: '🌻', color: 'bg-pink-500' },
    { id: 'german', title: 'German', icon: '🇩🇪', color: 'bg-indigo-400' },
    { id: 'flagsCars', title: 'Flags & Cars', icon: '🇮🇳', color: 'bg-slate-400' },
    { id: 'rhymes', title: 'Rhymes Library', icon: '🎵', color: 'bg-teal-500' }
];
